apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    app.kubernetes.io/name: godjira
    app.kubernetes.io/part-of: godjira
    app.kubernetes.io/managed-by: {{ .Release.Service }}
