# ServiceMonitor for Prometheus Operator to scrape metrics from API
# Requires Prometheus Operator to be installed

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: godjira-api
  namespace: godjira
  labels:
    app: api
    release: prometheus  # Match your Prometheus Operator release name
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /api/v1/metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - godjira
