apiVersion: v2
name: godjira
description: Enterprise-grade JIRA clone - Agile project management system
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - jira
  - project-management
  - agile
  - scrum
  - kanban
home: https://github.com/yourorg/godjira
sources:
  - https://github.com/yourorg/godjira
maintainers:
  - name: GodJira Team
    email: admin@godjira.example.com
