{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: godjira-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.api.name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.prometheus.serviceMonitor.path }}
      interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Values.global.namespace }}
{{- end }}
